name: pond_hockey
description: Pond Hockey Tournament Application

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^4.0.4
  enum_to_string: ^1.0.8
  shared_preferences: ^0.5.6+1
  google_fonts: ^0.3.9
  flutter_statusbarcolor: ^0.2.3
  auto_route: ^0.2.2
  uuid: ^2.0.4
  assorted_layout_widgets: ^1.0.15
  intl: ^0.16.1
  flutter_form_builder: ^3.8.0+1

  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^0.1.6
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+4
  sealed_flutter_bloc: ^3.0.0
  apple_sign_in: ^0.1.0

  # Firebase
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  firebase_database: ^3.1.1
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.1.4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
