name: pond_hockey
description: Pond Hockey Tournament Application

version: 1.1.7+12

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.3.9
  auto_route: ^0.4.1
  uuid: ^2.0.4
  intl: ^0.16.1
  flutter_form_builder: ^3.8.1
  enough_mail: ^0.0.5
  datetime_picker_formfield: ^1.0.0
  flutter_svg: ^0.17.3+1
  in_app_purchase: ^0.3.1+2

  # Bloc
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  sealed_flutter_bloc: ^3.0.0
  form_bloc: ^0.10.4
  flutter_form_bloc: ^0.10.7

  # Firebase
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.2.0
  apple_sign_in: ^0.1.0
  url_launcher: ^5.4.2
  package_info: ^0.4.0+14
  firebase_remote_config: ^0.3.0+3

  md2_tab_indicator: ^1.0.2
  loading_animations: ^2.1.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  effective_dart: ^1.2.1
  auto_route_generator: ^0.4.0
  build_runner: ^1.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - google_fonts/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/Regular.otf
          weight: 400
        - asset: assets/fonts/CircularStd/Medium.otf
          weight: 500
        - asset: assets/fonts/CircularStd/Bold.otf
          weight: 600
        - asset: assets/fonts/CircularStd/Black.otf
          weight: 900
